specify python version for evaluation.py
this is because raspi was executing this with python2 by default
which led to an error:
  File "evaluation.py", line 204, in <module>
    instances[instancename]['colnonzeros'] = float(outlines[idx+13].split()[3])
ValueError: invalid literal for float(): 383/97
however this works fine with python3